[tool.poetry]
name = "hacs-hubitat"
version = "0.5.1"
description = "A Hubitat integration for Home Assistant"
authors = ["Jason Cheatham <jason@jasoncheatham.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.4"
pytest-asyncio = "^0.12.0"
homeassistant = "^0.110.0"
black = "^19.10b0"
flake8 = "^3.8.1"
mypy = "^0.770"
isort = "^4.3.21"
pre-commit = "^2.4.0"
flake8-pyi = "^20.5.0"
hubitatmaker = "^0.3.9"
pytest-aiohttp = "^0.3.0"
asynctest = "^0.13.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
