clear_lock_code:
  description: Delete a user code from a lock
  fields:
    entity_id:
      description: Entity ID of a lock
    position:
      description: Index of code to delete
      example: 1
 
set_lock_code:
  description: Set a user code for a lock
  fields:
    entity_id:
      description: Entity ID of a lock
    position:
      description: Index of code to set
      example: 1
    code:
      description: Code
      example: 5213
    name:
      description: Friendly name for code
      example: Family
 
set_lock_code_length:
  description: Set the length of user codes for a lock
  fields:
    entity_id:
      description: Entity ID of a lock
    length:
      description: Length of acceptable codes
      example: 4
