name: Issue Assigned

on:
  issues:
    types: [assigned]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.1.2
        with:
          project: Development
          column: In progress
          repo-token: ${{ secrets.PA_TOKEN }}
