name: Issue Assigned

on:
  issues:
    types: [assigned]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/project-manager
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project: Development
          column: In progress
